### ISSUE TITLE
Curvatura

### ISSUE THREAD

**Issue by davelab6** [MFEK/glif#245] opened 2022-01-07 19:45 UTC
I expect its table stakes to have a tool like https://github.com/linusromer/curvatura in a glyph editor in 2022 :)

**Comment by ctrlcctrlv** [comment] 2022-01-07 21:38
Thanks. Duplicate of #19 and #20. Recently followed up in https://github.com/fontforge/fontforge/discussions/4879#discussioncomment-1918885.

**Closed by ctrlcctrlv** 2022-01-07 21:38 UTC
